addSbtPlugin("org.typelevel" % "sbt-typelevel" % "0.7.7")
addSbtPlugin("org.scala-js" % "sbt-scalajs" % "1.16.0")
addSbtPlugin("org.portable-scala" % "sbt-scalajs-crossproject" % "1.3.2")
addSbtPlugin("com.fiatjaf" %% "sbt-esbuild" % "0.1.1")
addSbtPlugin("io.chrisdavenport" % "sbt-npm-dependencies" % "0.0.1")
